### PR TITLE
Change database systems

### PR DESCRIPTION
**Pull request by latekvo**
Removing legacy TinyDB instances, they operate mainly in-memory, only ocassionally flushing to fs, which is highly undesireable.

Will be replacing them with SQLAlchemy, and likely hooking up PostgreSQL to it due to it's scalability.
We'll also need a document db, first candidate is of course Mongo but this is up for debate.

I think I'll also separate the downloaded documents out of the url_db and the summaries out of the summary_tasks db, into a pure document database.
This will allow us to have all the main databases to be Postgres, while using document based dbs only for pure text variable length data.

### CODE REVIEW

**Comment by latekvo** [comment]
This should be remembered, not sure what would be a good way of saving this info.
`session.scalars(query).one()` automatically raises an error when no results are found.

**Comment by latekvo** [comment]
Everything's ready, will test it better tomorrow, we'll have to dockerize postgres asap, that'll complete the entire thing i think.
Also, for now all the dbs are memory-kept, still SQL just in memory.

**Comment by latekvo** [comment]
summarizer is now working since the latest commit

**Comment by latekvo** [comment]
all workers are now launching :partying_face:

**Review by Nekxis — APPROVED** [review]
:shipit:

**Comment by latekvo** [comment]
(c.c. @SOSNE ) :rock:

**Review by SOSNE — APPROVED** [review]
Looks good to me

**Pull request merged**
