### PR TITLE
Fix missing expunges and other statements

### PR DESCRIPTION
**Pull request by latekvo**

### CODE REVIEW

**Comment by latekvo** [comment]
Todo!

Currently:
> summarizer gets a task, schedules a crawl for it, and pings the db to see if the crawl is completed

How it should be:
> summarizer gets a task, schedules a crawl for it, and lets it go. Then pings the db for any free, ready tasks.

**Comment by latekvo** [comment]
We're home boys :D

**Review by SOSNE — APPROVED** [review]
good job for everyone ❤️

**Review by dawid-jamka — APPROVED** [review]
Finally :)

**Pull request merged**
