### PR TITLE
Make workers launch from main, refactor config system

### PR DESCRIPTION
**Pull request by latekvo**

### CODE REVIEW

**Comment by latekvo** [comment]
I see a lot of instances of code execution outside of any function, example:

```py
runtime_configuration = get_runtime_config()
llm_config = runtime_configuration.llm_config
embedder_config = runtime_configuration.embedder_config
```

Now I'd have to check, but I am relatively sure that may be a problem, and may cause problems when importing certain files in wrong order, etc.

I agree that this approach simplifies code, but i can also see how it could hinder debugging by introducing a non-linear flow.

I am writing this down just to remember to try and refactor as much of these instances as I can before merging this PR.

**Comment by latekvo** [comment]
Such a cute lil error :3
Someone could make this into a standalone library
image

edit: it's now wrapped into a small function inside `core/tools/errorlib.py` :)

**Comment by latekvo** [comment]
@Nekxis plz test on your hvper mvssive lvnux bveast :)

**Review by Nekxis — APPROVED** [review]
looks good :shipit:

**Review by pawelcp — APPROVED** [review]

**Review by SOSNE — APPROVED** [review]
Looks great 👀

**Pull request merged**
