### PR TITLE
App dockerization

### PR DESCRIPTION
**Pull request by Nekxis**
dockerization of workers

### CODE REVIEW

**Comment by latekvo** [comment]
what's left to do here? 
i'd really like to merge this asap

**Comment by Nekxis** [comment]
when postgres is ready it has to be merged into this branch and then dockerized, only after that application will work with dockerazation

**Comment by latekvo** [comment]
Managed to get all workers running steadily by increasing their timeout, after 15 minutes number of open sessions stabilizes at 42, suggesting we have a `Session` leak happening somewhere, which is strange because for every session, we're using the `with` clause which should be closing them automatically.
Current short term goals for improvement:
- solve the `Session` issue
- decrease `noisy_sleep` as low as possible, should be no higher than `2`

**Comment by latekvo** [comment]
I confirm that all the leaks (while idling) as well as the integer overflow have been fixed

**Comment by latekvo** [comment]
crawler managed to work on over 200 tasks with no failure :tada:

**Review by latekvo — APPROVED** [review]
Looks good to me, `summarizer` still needs some work, and `embedder` won't work without `FAISS` being dockerized, but rest looks solid.

**Pull request merged**
