### PR TITLE
Fixing the fastapi server

### PR DESCRIPTION
**Pull request by dawid-jamka**
-Make fastapi server working again;
-Need to handle the argument parsing;
-Commented out arguments.py file and hardcoded constants for now; 
-Resolve issue with bad naming and location of the db_get_incomplete_completion_tasks function;

### CODE REVIEW

**Comment by latekvo** [comment]
just so you know, these conflicts you see are already resolved in the other PR, so don't worry about them

**Review by Nekxis — APPROVED** [review]
good job :shipit:

**Review by latekvo — APPROVED** [review]
No idea which changes are mine and which are yours lol
:shaking_face: :shipit:

**Comment by Nekxis** [comment]
so that makes two of us :1st_place_medal:

**Comment by latekvo** [comment]
help i accidentally allowed this PR to be merged

**Pull request merged**
