### PR TITLE
Added navigation for Header component

### PR DESCRIPTION
**Pull request by pawelcp**

### CODE REVIEW

**Comment by latekvo** [comment]
ok

**Comment by pawelcp** [comment]
OK?

**Comment by latekvo** [comment]
package-lock much?

**Comment by pawelcp** [comment]
nie ok?

**Comment by Nekxis** [comment]
8,500+ ???

**Comment by pawelcp** [comment]
only?

**Review by latekvo — COMMENTED** [review]
Sir, are you certain of the needfulness of the `package-lock.json` file?

**Comment by pawelcp** [comment]
yes sir

**Comment by SOSNE** [comment]
🚀  to the moon

**Review by latekvo — APPROVED** [review]
Sir, you commited the needful and I appreciate your engagement. :smile: 
Honest Love from Poland :poland: 
Ignacy :heart:

**Review by SOSNE — APPROVED** [review]
Good work 🥇

**Pull request merged**
